"""Init

Revision ID: 3f10b6074709
Revises: 05113834b542
Create Date: 2023-02-15 21:35:33.786382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f10b6074709'
down_revision = '05113834b542'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('birthday', sa.Date(), nullable=True))
    op.drop_index('ix_contacts_birhday', table_name='contacts')
    op.create_index(op.f('ix_contacts_birthday'), 'contacts', ['birthday'], unique=False)
    op.drop_column('contacts', 'birhday')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('birhday', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_contacts_birthday'), table_name='contacts')
    op.create_index('ix_contacts_birhday', 'contacts', ['birhday'], unique=False)
    op.drop_column('contacts', 'birthday')
    # ### end Alembic commands ###
